Feature/chatting
leehyunjun97/ggeu-jeok pull request #7
Opened 2023-11-03 10:09 UTC by leehyunjun97

## 작업내용 🛠

-실시간으로 채팅 가져오기 및 전송 기능 추가

-사용방법
  - 아이디: lee2@naver.com 비밀번호: 123456
  - 만들어져 있는 방 들어가서 아무 채팅 ( shift+enter 전송 )

## 체크 리스트 ✅

- [ ] reviewer, asignee, label을 설정 했습니다.
- [x] 구현한 기능이 잘 동작하는지 직접 브라우저에서 확인/테스트 했습니다.
- [ ] 외부 의존성 라이브러리의 변경점이 있어서 npm install(or yarn)을 실행해야 합니다.

## 스크린샷 🌠

- N/A

## 참고사항 📖

firebase key 두 개 사용했던거 하나로 합침 (이미지, reatime, firestore)

2023-11-03 19:04 UTC, AnJuhwan commented
일단 버그가 너무 많아요. 
코드리뷰 하기전 버그부터 고쳐주세요.

버그목록 :
1.  Make a plan 생성 누르면 생성 계속됨. (라우터가 되지 않음)
2. 지역을 선택 할 수 없음 (너무 불친절함) - 다른 지역을 선택하려면 못함
3. 친구 요청 보낼 때 폰트 색상 하얀색이에요 (안보입니다.)
4. 채팅 한쪽에서만 보내지고 다른 한쪽에서 안보내집니다.
5. 이미지 못찾을땐 default image 삽입해주세요.
6. 일정관리하는 곳에서 새로고침하면 `Invalid collection reference.` 에러 뜹니다.
7. 날짜마다 제목 입력하는곳 수정할때마다 정렬이 이상한데 의도된건가요?
8. 날짜 일정 + 버튼 뭔가 계속 누르게 되는데 아무것도 동작되지 않아요.. (뺴거나 뭔가 동작을 해야할 거 같은 느낌..?)

2023-11-03 19:15 UTC, AnJuhwan requested changes
고쳐야할 목록
1. 친구추가 할 때 폰트 색상 하얀색
2. 내 위치말고 다른 지역에 있는 위치는 선택 불가능 (내위치도 되는지 모르겠음)
3. (할 일)  방 생성하기 누르고나서 아무런 동작이 없음 (라우팅 되야될 거 같음) - 계속 방이 생성됨
4. 날짜마다 해당 제목들 입력하고 나오면 정렬이 이상해짐 - 의도된건가..?
5. image url 못찾을때는 default image 사용해주면 좋을 거 같음
6. 날짜마다 해당 제목들 있는 페이지에서 리프레쉬하면 에러남
7. 채팅이 한쪽에서만 보내지고 다른한쪽에서는 안보내짐

코드리뷰 전에 버그부터 해결하는게 좋아보여서 코드리뷰는 안남길게요
채팅쪽이니 (6 , 7) 버그 해결 부탁드립니다.

2023-11-05 06:08 UTC, leehyunjun97 commented
- 수정 완료
날짜마다 해당 제목들 있는 페이지에서 리프레쉬하면 에러남
채팅이 한쪽에서만 보내지고 다른한쪽에서는 안보내짐
shift + enter을 눌러야 다음줄 이동이 원래 정상적인게 아닌가.. 건의해봄
shift + enter 연타하면 2~3번 같은 메세지가 날라감

2023-11-07 09:07 UTC, AnJuhwan reviewed
고생하셨습니다.
이거는 저도 협업하면서 느끼는거지만 내가 짠 컴포넌트들이 다른사람들이 쓰려고할 때 상황에 맞게 쓸 수 있는지, 한눈에 들어오는 컴포넌트인지, 어떤 의도를 가지고 있는 프로퍼티 & 네이밍 인지 생각하며서 컴포넌트를 짜신다면 더욱 좋아지실 거 같아요

2023-11-07 09:07 UTC, AnJuhwan commented on src/pages/schedule/CreateRoom/CreateRoom.tsx
> +            setRoomInfo({ ...room, location: lo });
💊 `lo` ...? 네이밍에 신경써주세요!

2023-11-07 09:07 UTC, AnJuhwan commented on src/pages/schedule/DetailRoom/TitleSection.tsx
> +            }}
💊 이것도 위에 코드처럼 바꿔보시길 바래요!

2023-11-07 09:07 UTC, AnJuhwan commented on src/pages/signup/Signup.tsx
> +              style={emailDisable ? { opacity: '0.5' } : { opacity: '1' }}
💊 `style={{opacity:emailDisable ?  '0.5' : '1' }}` 로 고쳐볼 수 있을거 같아요

2023-11-07 09:07 UTC, AnJuhwan commented on src/utils/chat/chat.ts
> +};
❓ 음.. 해석해보자면 id 와 send_at 시간을 넣어주는 함수인가요..?

2023-11-07 09:07 UTC, AnJuhwan commented on src/utils/common/date.ts
> +};
💬 직접 구현한것도 좋지만 `dayjs` 라는 잘되어있는 라이브러리가 있어요!
    나중에 한번 기회되면 써보십시요

2023-11-07 09:33 UTC, leehyunjun97 commented on src/components/Chat/ChatCard.tsx
> +          </div>
수정 완료

2023-11-07 09:34 UTC, leehyunjun97 commented on src/components/Chat/ChattingDiv.tsx
chatting이 보이는 Div라 네이밍 한거고
getCom은 get api의 Complet이 됐을 때 리턴 되는 값을 담는 변수라 지은 건데 좀 더 신중하게 지어보도록 하겠습니다

2023-11-07 09:37 UTC, leehyunjun97 commented on src/components/common/Button/Button.tsx
> +  refusaaText?: string;
좀 더 포괄적으로 의미를 담을 수 있겠네요

2023-11-07 09:55 UTC, leehyunjun97 commented on src/utils/chat/chat.ts
> +};
addIdAndSentAtToSnapshot 으로 변경 완료

2023-11-07 18:43 UTC, leehyunjun97 commented on src/pages/schedule/CreateRoom/CreateRoom.tsx
> +        navigate(`/main`);
없네요잉

2023-11-10 00:50 UTC, AnJuhwan reviewed
👍

2023-11-10 00:50 UTC, AnJuhwan commented on src/components/common/Img/Img.tsx
> +  clickFunc?: () => void;
💊 `clickFunc` 네이밍도 `onClick` HTML 프로퍼티를 따라가면 좋을 거 같습니다.
       대중적으로 사용하는 이벤트 이름들은 ex) `onChange & onClick & onDrop & onError ... ` 들은
       친숙한 HTML 프로퍼티 네이밍을 따라갑시다.

2023-11-10 00:50 UTC, AnJuhwan commented on src/components/common/Img/Img.tsx
> +  src?: string;
💊 `Image` 태그인데 src는 필수값으로 정의해도 되지 않을까요?
❓ 옵셔널 값으로 처리하신 이유가 있으신가요?

2023-11-10 00:50 UTC, AnJuhwan commented on src/utils/common/keyDown.ts
> +};
❗️mac에서는 `shiftKey` 가 없어서 전송으로 클릭해야 보내집니다.
     보내는건 Enter만으로 바꾸시는건 어떠실까요?

2023-11-10 09:16 UTC, merged